# Generated by Django 5.2.7 on 2025-11-18 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_setup', '0002_position_alter_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='home_setup.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
